import type { CSSProperties } from "react";

export const S: Record<string, CSSProperties> = {
  wrap: { display: "flex", flexDirection: "column", height: "100%", minHeight: 0,
    background: "#0e0e12", color: "#e7e7ee" },
  bar: { display: "flex", alignItems: "center", gap: 16, padding: "10px 16px",
    borderBottom: "1px solid #2a2a34" },
  graphTools: { display: "flex", alignItems: "center", gap: 7, padding: "7px 16px",
    borderBottom: "1px solid #24242d", background: "#111117", overflowX: "auto" },
  graphSearch: { flex: "1 1 240px", minWidth: 180, display: "flex", alignItems: "center",
    gap: 7, height: 32, padding: "0 9px", border: "1px solid #30303a", background: "#0b0b10" },
  graphSearchInput: { flex: 1, minWidth: 0, border: 0, outline: 0, background: "transparent",
    color: "#dce5e0", fontSize: 11 },
  graphControl: { height: 32, padding: "0 9px", border: "1px solid #30303a",
    background: "#17171e", color: "#a6aaa8", fontSize: 10, whiteSpace: "nowrap" },
  filterCount: { marginLeft: "auto", color: "#758079", font: "10px ui-monospace,monospace",
    whiteSpace: "nowrap" },
  toolActive: { borderColor: "#537a5e", color: "#71dfa0", background: "#132018" },
  credentialOverlayActive: { borderColor: "#7b6734", color: "#e3b341",
    background: "#1c1709" },
  tabs: { display: "flex", flexShrink: 0, gap: 4, background: "#16161c", padding: 4,
    borderRadius: 10, border: "1px solid #2a2a34" },
  legend: { marginLeft: "auto", minWidth: 0, overflowX: "auto", display: "flex",
    flexWrap: "nowrap", gap: 12, color: "#9a9aa6", fontSize: 12 },
  stage: { flex: 1, display: "flex", minHeight: 0 },
  hint: { position: "absolute", left: 16, bottom: 14, color: "#6b6b76", fontSize: 12,
    pointerEvents: "none" },
  activityStream: { position: "absolute", minWidth: 184, minHeight: 34,
    display: "flex", flexDirection: "column", overflow: "hidden",
    border: "1px solid rgba(89,245,154,.22)",
    background: "rgba(8,12,11,.94)", backdropFilter: "blur(8px)", color: "#d8e2dd" },
  activityHead: { flex: "0 0 auto", zIndex: 1, display: "flex",
    justifyContent: "space-between", padding: "8px 10px", borderBottom: "1px solid #223029",
    background: "rgba(8,12,11,.96)", color: "#59f59a", cursor: "move",
    touchAction: "none", userSelect: "none",
    font: "600 9px ui-monospace,monospace", letterSpacing: 1 },
  activityHeadActions: { display: "flex", alignItems: "center", gap: 8 },
  activityToggle: { width: 22, height: 20, padding: 0, border: "1px solid #294036",
    background: "#101a15", color: "#75d99c", cursor: "pointer",
    font: "600 10px ui-monospace,monospace" },
  activityTools: { flex: "0 0 auto", padding: "10px", borderBottom: "1px solid #223029",
    background: "#0b100e" },
  activitySearch: { height: 34, display: "flex", alignItems: "center", gap: 7,
    padding: "0 9px", border: "1px solid #314139", background: "#060a08", color: "#6f8379" },
  activitySearchInput: { flex: 1, minWidth: 0, padding: 0, border: 0, outline: 0,
    background: "transparent", color: "#e0e8e4", fontSize: 11 },
  activitySearchClear: { width: 22, height: 22, padding: 0, border: 0,
    background: "transparent", color: "#84938b", cursor: "pointer", fontSize: 15 },
  activityFilters: { display: "grid", gridTemplateColumns: "1fr 1fr auto", gap: 6, marginTop: 8 },
  activityControl: { minWidth: 0, height: 30, padding: "0 8px", border: "1px solid #314139",
    background: "#0c1410", color: "#aebdb5", cursor: "pointer", fontSize: 10 },
  activityList: { flex: 1, minHeight: 0, overflow: "auto", paddingBottom: 14 },
  // A single flowing scrollback line instead of a card: timestamp, status
  // dot, then the event text with its kind/reason folded into a dim
  // trailing note on the same line -- reads top-to-bottom like `tail -f`,
  // not a list of summary tiles.
  activityRow: { width: "100%", display: "flex", alignItems: "baseline",
    gap: 7, padding: "3px 10px", border: 0, background: "transparent",
    color: "#d2ddd7", textAlign: "left", cursor: "pointer",
    font: "11px/1.6 ui-monospace,monospace", whiteSpace: "nowrap",
    overflow: "hidden", textOverflow: "ellipsis" },
  activityDot: { width: 6, height: 6, flexShrink: 0, borderRadius: "50%" },
  activityCopy: { minWidth: 0, overflow: "hidden", textOverflow: "ellipsis" },
  activityMeta: { color: "#5a6f68" },
  activityTime: { flexShrink: 0, color: "#4a5c55", fontSize: 10, fontVariantNumeric: "tabular-nums" },
  activityEmpty: { padding: 20, color: "#75837c", fontSize: 11, textAlign: "center" },
  activityResize: { position: "absolute", right: 1, bottom: 1, zIndex: 3,
    width: 22, height: 22, display: "grid", placeItems: "center", color: "#68d594",
    background: "#101a15", borderLeft: "1px solid #31533f", borderTop: "1px solid #31533f",
    cursor: "nwse-resize", touchAction: "none", userSelect: "none", fontSize: 14 },
  activityResizeTop: { width: 22, height: 20, display: "grid", placeItems: "center",
    border: "1px solid #294036", background: "#101a15", color: "#75d99c",
    cursor: "nwse-resize", touchAction: "none", fontSize: 11 },
  inspectorTitle: { display: "flex", alignItems: "center", justifyContent: "space-between",
    gap: 10 },
  nodeNotes: { display: "grid", gap: 7, marginTop: 14, padding: 10,
    border: "1px solid #2a2a34", background: "#111117" },
  taskQueue: { position: "fixed", zIndex: 55, right: 24, top: 150, width: 360,
    maxHeight: "calc(100vh - 180px)", overflow: "auto", border: "1px solid #31513e",
    background: "#0b100e", color: "#d8e2dd", boxShadow: "0 18px 50px rgba(0,0,0,.45)" },
  taskAdd: { width: "calc(100% - 20px)", margin: 10, padding: 9,
    border: "1px solid #365743", background: "#14241a", color: "#74dfa0" },
  taskList: { borderTop: "1px solid #26352d" },
  taskItem: { display: "grid", gridTemplateColumns: "1fr auto", gap: 8, padding: 9,
    borderBottom: "1px solid #222e28" },
  quickMenuBackdrop: { position: "fixed", inset: 0, zIndex: 80 },
  quickMenu: { position: "fixed", width: 200, margin: 0, padding: 6,
    border: "1px solid #35453d", background: "#101512", color: "#d8e2dd",
    boxShadow: "0 14px 40px rgba(0,0,0,.55)" },
  outline: { flex: 1, overflow: "auto", padding: 18 },
  row: { display: "flex", alignItems: "center", gap: 8, padding: "5px 8px",
    borderRadius: 7, cursor: "pointer" },
  rowSel: { background: "rgba(106,169,255,.12)",
    boxShadow: "inset 0 0 0 1px rgba(106,169,255,.25)" },
  inspector: { flex: 1, minWidth: 0, background: "#16161c",
    padding: 16, overflow: "auto" },
  executionResults: { marginTop: 18, border: "1px solid #2a2a34",
    borderRadius: 8, overflow: "hidden", background: "#101016" },
  executionResultsHead: { display: "flex", alignItems: "center", gap: 8,
    justifyContent: "space-between", padding: "10px 12px",
    borderBottom: "1px solid #2a2a34", fontSize: 12 },
  // Terminal chrome for the "실행 결과" panel -- a real command run, dressed
  // up as a shell session instead of a report card, since the graph is
  // meant to feel like it's handing you commands rather than a dashboard.
  terminalTitlebar: { display: "flex", alignItems: "center", gap: 10,
    padding: "8px 12px", background: "#161b17", borderBottom: "1px solid #223028" },
  terminalDots: { display: "flex", gap: 6, flexShrink: 0 },
  terminalDot: { width: 10, height: 10, borderRadius: 10, display: "inline-block" },
  terminalTitle: { flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis",
    whiteSpace: "nowrap", font: "11px ui-monospace,monospace", color: "#7fae8f" },
  terminalBody: { background: "#080b09", padding: "10px 12px 4px" },
  terminalPromptLine: { font: "11px/1.6 ui-monospace,monospace", color: "#59f59a",
    whiteSpace: "pre-wrap", overflowWrap: "anywhere", marginBottom: 8 },
  terminalPrompt: { color: "#3ecf7a", marginRight: 6 },
  terminalComment: { font: "10px ui-monospace,monospace", color: "#3d5245",
    padding: "6px 0 4px", cursor: "pointer", userSelect: "none" },
  terminalOutput: { margin: 0, padding: "0 0 10px", background: "transparent",
    color: "#c8ded4", font: "10px/1.55 ui-monospace,monospace",
    whiteSpace: "pre-wrap", overflowWrap: "anywhere", maxHeight: 320, overflow: "auto" },
  terminalOutputError: { margin: 0, padding: "0 0 10px", background: "transparent",
    color: "#f28b82", font: "10px/1.55 ui-monospace,monospace",
    whiteSpace: "pre-wrap", overflowWrap: "anywhere", maxHeight: 320, overflow: "auto" },
  resultAction: { border: "1px solid #454552", borderRadius: 6, padding: "5px 8px",
    background: "#22222b", color: "#e7e7ee", fontSize: 10 },
  resultNotice: { padding: "8px 12px", color: "#8ed1a9", fontSize: 10,
    borderBottom: "1px solid #2a2a34" },
  resultError: { padding: "8px 12px", color: "#e3938c", fontSize: 10,
    borderBottom: "1px solid #2a2a34" },
  resultMessage: { padding: 12, color: "#9a9aa6", fontSize: 11 },
  linkList: { maxHeight: 420, overflow: "auto" },
  linkRow: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) 80px auto",
    alignItems: "center", gap: 10, padding: "9px 12px",
    borderBottom: "1px solid #22222b" },
  linkHeader: { position: "sticky", top: 0, zIndex: 1, background: "#15151c",
    color: "#9a9aa6", fontSize: 10 },
  linkCode: { minWidth: 0, overflowWrap: "anywhere", color: "#d7dedb", fontSize: 11 },
  linkKind: { color: "#9a9aa6", fontSize: 10, whiteSpace: "nowrap" },
  rowAction: { border: "1px solid #454552", borderRadius: 5, padding: "4px 7px",
    background: "#22222b", color: "#e7e7ee", fontSize: 9, whiteSpace: "nowrap" },
  captureList: { display: "grid", gap: 8, padding: 10 },
  captureCard: { padding: 11, border: "1px solid #2d493a", borderRadius: 6,
    background: "#0b120e" },
  captureHead: { display: "flex", justifyContent: "space-between", gap: 8,
    color: "#dce8e1", fontSize: 11 },
  captureMeta: { marginTop: 4, color: "#72847a", fontSize: 9 },
  captureValue: { display: "block", marginTop: 10, padding: 9, maxHeight: 120,
    overflow: "auto", overflowWrap: "anywhere", whiteSpace: "pre-wrap",
    border: "1px solid #24352c", background: "#060a08", color: "#67e89b",
    font: "9px/1.45 ui-monospace,monospace" },
  captureActions: { display: "flex", flexWrap: "wrap", gap: 6, marginTop: 8 },
  requestPanel: { flex: 1, minWidth: 0, overflow: "auto", padding: 18,
    background: "#101317", color: "#dce8e1" },
  requestPanelHead: { display: "flex", justifyContent: "space-between",
    alignItems: "center", paddingBottom: 16, borderBottom: "1px solid #29332e" },
  requestEyebrow: { color: "#59f59a", font: "9px ui-monospace,monospace",
    letterSpacing: 2 },
  requestBack: { border: 0, background: "transparent", color: "#8fa099",
    cursor: "pointer", fontSize: 11 },
  requestLine: { display: "flex", gap: 0, marginTop: 18,
    border: "1px solid #365345", background: "#090d0b" },
  requestMethod: { width: 92, border: 0, borderRight: "1px solid #365345",
    background: "#132219", color: "#59f59a", padding: "11px 10px",
    font: "600 11px ui-monospace,monospace" },
  requestUrl: { minWidth: 0, flex: 1, border: 0, outline: 0, padding: "11px 12px",
    background: "transparent", color: "#dce8e1", font: "11px ui-monospace,monospace" },
  requestSend: { width: 76, border: 0, borderLeft: "1px solid #365345",
    background: "#173824", color: "#72f7a8", cursor: "pointer",
    font: "700 10px ui-monospace,monospace", letterSpacing: 1 },
  responderInsert: { maxWidth: 190, border: 0, borderLeft: "1px solid #61303a",
    padding: "0 12px", background: "#281118", color: "#ff7188", cursor: "pointer",
    font: "600 9px ui-monospace,monospace", whiteSpace: "nowrap" },
  requestGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))",
    gap: 10, marginTop: 12 },
  requestField: { display: "grid", gap: 6, color: "#789086",
    font: "9px ui-monospace,monospace", letterSpacing: 1 },
  requestActions: { display: "flex", alignItems: "center", flexWrap: "wrap",
    gap: 10, marginTop: 12, color: "#8fa099", fontSize: 10 },
  requestSaved: { color: "#59f59a", font: "9px ui-monospace,monospace" },
  responsePanel: { marginTop: 18, border: "1px solid #29332e", background: "#090d0b" },
  responseHead: { display: "flex", justifyContent: "space-between", padding: "10px 12px",
    borderBottom: "1px solid #29332e", color: "#59f59a",
    font: "9px ui-monospace,monospace" },
  responsePre: { maxHeight: 360, overflow: "auto", margin: 0, padding: 12,
    color: "#bcd0c5", whiteSpace: "pre-wrap", overflowWrap: "anywhere",
    font: "10px/1.55 ui-monospace,monospace" },
  requestEmpty: { padding: 32, textAlign: "center", color: "#617069", fontSize: 11 },
  embedPane: { flex: 1, minWidth: 0, overflow: "auto", minHeight: 0,
    background: "#0e0e12" },
  splitter: { width: 6, flexShrink: 0, cursor: "col-resize", background: "#2a2a34",
    borderLeft: "1px solid #0e0e12", borderRight: "1px solid #0e0e12",
    touchAction: "none" },
  openBtn: { marginTop: 18, width: "100%", padding: "9px 12px", borderRadius: 8,
    border: "1px solid #6aa9ff55", background: "#6aa9ff14", color: "#6aa9ff",
    fontWeight: 600, cursor: "pointer" },
  hideBtn: { marginTop: 10, width: "100%", padding: "8px 12px", borderRadius: 8,
    border: "1px solid #2a2a34", background: "transparent", color: "#9a9aa6",
    fontWeight: 500, cursor: "pointer" },
  hiddenChip: { padding: "5px 12px", borderRadius: 8, border: "1px solid #2a2a34",
    background: "#16161c", color: "#9a9aa6", fontSize: 12, fontWeight: 600,
    cursor: "pointer" },
  field: { width: "100%", padding: "8px 10px", borderRadius: 6,
    border: "1px solid #2a2a34", background: "#0e0e12", color: "#e7e7ee",
    fontSize: 13 },
  overlay: { position: "fixed", inset: 0, zIndex: 60, background: "rgba(0,0,0,.45)",
    display: "flex", alignItems: "flex-start", justifyContent: "center",
    paddingTop: 90 },
};
